In [1]:
import numpy as np

arr = np.random.randint(5, 21, size=(3, 3))
print("Array:\n", arr)

row_means = arr.mean(axis=1)
print("Mean of each row:", row_means)


Array:
 [[ 6 14  9]
 [19 12 16]
 [15  6 14]]
Mean of each row: [ 9.66666667 15.66666667 11.66666667]


In [1]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Score": [85, 55, 72, 40]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

filtered_df = df[df["Score"] >= 60]
print("Filtered DataFrame:\n", filtered_df)


Original DataFrame:
       Name  Score
0    Alice     85
1      Bob     55
2  Charlie     72
3    David     40
Filtered DataFrame:
       Name  Score
0    Alice     85
2  Charlie     72


In [2]:
def normalize(values):
    min_val = min(values)
    max_val = max(values)
    return [(x - min_val) / (max_val - min_val) for x in values]

nums = [10, 20, 30, 40]
print(normalize(nums))


[0.0, 0.3333333333333333, 0.6666666666666666, 1.0]


In [4]:
import numpy as np
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

result = np.dot(A, B)

print("Matrix multiplication result:\n", result)


Matrix multiplication result:
 [[19 22]
 [43 50]]


In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
heart = pd.read_csv("heart.csv")


In [10]:
print("Shape of dataset:", heart.shape)


Shape of dataset: (303, 14)


In [11]:
print("Missing values per column:\n", heart.isnull().sum())


Missing values per column:
 age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64


In [12]:
print("Data types:\n", heart.dtypes)


Data types:
 age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object


In [14]:
print("Mean age:", heart["age"].mean())


Mean age: 54.366336633663366


In [15]:
selected_columns = ["age", "sex", "cp", "restecg", "chol"]
heart_selected = heart[selected_columns]

train_data, test_data = train_test_split(
    heart_selected,
    test_size=0.25,
    random_state=42
)

print("Training set shape:", train_data.shape)
print("Testing set shape:", test_data.shape)


Training set shape: (227, 5)
Testing set shape: (76, 5)
